
package com.echelon.wsdl.panoramix;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeviceManagerSoap", targetNamespace = "http://wsdl.echelon.com/Panoramix/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DeviceManagerSoap {


    /**
     * 
     * @param sDeviceID
     * @param sValueID
     * @param sKey
     * @param sAttributeID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AssignDefinedAttributeValue", action = "http://wsdl.echelon.com/Panoramix/AssignDefinedAttributeValue")
    @WebResult(name = "AssignDefinedAttributeValueResult", partName = "AssignDefinedAttributeValueResult")
    public String assignDefinedAttributeValue(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sAttributeID", partName = "sAttributeID")
        String sAttributeID,
        @WebParam(name = "sValueID", partName = "sValueID")
        String sValueID);

    /**
     * 
     * @param sDeviceID
     * @param sKey
     * @param sHierarchyLevelMemberID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AssignHierarchy", action = "http://wsdl.echelon.com/Panoramix/AssignHierarchy")
    @WebResult(name = "AssignHierarchyResult", partName = "AssignHierarchyResult")
    public String assignHierarchy(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sHierarchyLevelMemberID", partName = "sHierarchyLevelMemberID")
        String sHierarchyLevelMemberID);

    /**
     * 
     * @param sDeviceID
     * @param dActualValue
     * @param sKey
     * @param sAttributeID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AssignNumericAttributeValue", action = "http://wsdl.echelon.com/Panoramix/AssignNumericAttributeValue")
    @WebResult(name = "AssignNumericAttributeValueResult", partName = "AssignNumericAttributeValueResult")
    public String assignNumericAttributeValue(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sAttributeID", partName = "sAttributeID")
        String sAttributeID,
        @WebParam(name = "dActualValue", partName = "dActualValue")
        double dActualValue);

    /**
     * 
     * @param sDeviceID
     * @param sValue
     * @param sKey
     * @param sAttributeID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AssignStringAttributeValue", action = "http://wsdl.echelon.com/Panoramix/AssignStringAttributeValue")
    @WebResult(name = "AssignStringAttributeValueResult", partName = "AssignStringAttributeValueResult")
    public String assignStringAttributeValue(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sAttributeID", partName = "sAttributeID")
        String sAttributeID,
        @WebParam(name = "sValue", partName = "sValue")
        String sValue);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @param sBatchID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CompleteResultBatch", action = "http://wsdl.echelon.com/Panoramix/CompleteResultBatch")
    @WebResult(name = "CompleteResultBatchResult", partName = "CompleteResultBatchResult")
    public String completeResultBatch(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sBatchID", partName = "sBatchID")
        String sBatchID,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Create", action = "http://wsdl.echelon.com/Panoramix/Create")
    @WebResult(name = "CreateResult", partName = "CreateResult")
    public String create(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateResultBatch", action = "http://wsdl.echelon.com/Panoramix/CreateResultBatch")
    @WebResult(name = "CreateResultBatchResult", partName = "CreateResultBatchResult")
    public String createResultBatch(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sDeviceID
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Delete", action = "http://wsdl.echelon.com/Panoramix/Delete")
    @WebResult(name = "DeleteResult", partName = "DeleteResult")
    public String delete(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteResultList", action = "http://wsdl.echelon.com/Panoramix/DeleteResultList")
    @WebResult(name = "DeleteResultListResult", partName = "DeleteResultListResult")
    public String deleteResultList(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Move", action = "http://wsdl.echelon.com/Panoramix/Move")
    @WebResult(name = "MoveResult", partName = "MoveResult")
    public String move(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PerformCommand", action = "http://wsdl.echelon.com/Panoramix/PerformCommand")
    @WebResult(name = "PerformCommandResult", partName = "PerformCommandResult")
    public String performCommand(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PerformCommandOnGroup", action = "http://wsdl.echelon.com/Panoramix/PerformCommandOnGroup")
    @WebResult(name = "PerformCommandOnGroupResult", partName = "PerformCommandOnGroupResult")
    public String performCommandOnGroup(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @param sBatchID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReleaseResultBatch", action = "http://wsdl.echelon.com/Panoramix/ReleaseResultBatch")
    @WebResult(name = "ReleaseResultBatchResult", partName = "ReleaseResultBatchResult")
    public String releaseResultBatch(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sBatchID", partName = "sBatchID")
        String sBatchID,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReleaseResultBatchItems", action = "http://wsdl.echelon.com/Panoramix/ReleaseResultBatchItems")
    @WebResult(name = "ReleaseResultBatchItemsResult", partName = "ReleaseResultBatchItemsResult")
    public String releaseResultBatchItems(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sDeviceID
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Retrieve", action = "http://wsdl.echelon.com/Panoramix/Retrieve")
    @WebResult(name = "RetrieveResult", partName = "RetrieveResult")
    public String retrieve(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sIDTypeID
     * @param sKey
     * @param sXmlParameters
     * @param sID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveByParameter", action = "http://wsdl.echelon.com/Panoramix/RetrieveByParameter")
    @WebResult(name = "RetrieveByParameterResult", partName = "RetrieveByParameterResult")
    public String retrieveByParameter(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sIDTypeID", partName = "sIDTypeID")
        String sIDTypeID,
        @WebParam(name = "sID", partName = "sID")
        String sID,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveCommandHistory", action = "http://wsdl.echelon.com/Panoramix/RetrieveCommandHistory")
    @WebResult(name = "RetrieveCommandHistoryResult", partName = "RetrieveCommandHistoryResult")
    public String retrieveCommandHistory(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sIDTypeID
     * @param sKey
     * @param sXmlParameters
     * @param sID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveDiscoveredInformation", action = "http://wsdl.echelon.com/Panoramix/RetrieveDiscoveredInformation")
    @WebResult(name = "RetrieveDiscoveredInformationResult", partName = "RetrieveDiscoveredInformationResult")
    public String retrieveDiscoveredInformation(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sIDTypeID", partName = "sIDTypeID")
        String sIDTypeID,
        @WebParam(name = "sID", partName = "sID")
        String sID,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveDiscoveredList", action = "http://wsdl.echelon.com/Panoramix/RetrieveDiscoveredList")
    @WebResult(name = "RetrieveDiscoveredListResult", partName = "RetrieveDiscoveredListResult")
    public String retrieveDiscoveredList(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveKeyList", action = "http://wsdl.echelon.com/Panoramix/RetrieveKeyList")
    @WebResult(name = "RetrieveKeyListResult", partName = "RetrieveKeyListResult")
    public String retrieveKeyList(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveList", action = "http://wsdl.echelon.com/Panoramix/RetrieveList")
    @WebResult(name = "RetrieveListResult", partName = "RetrieveListResult")
    public String retrieveList(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sResultID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveResult", action = "http://wsdl.echelon.com/Panoramix/RetrieveResult")
    @WebResult(name = "RetrieveResultResult", partName = "RetrieveResultResult")
    public String retrieveResult(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sResultID", partName = "sResultID")
        String sResultID);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveResultList", action = "http://wsdl.echelon.com/Panoramix/RetrieveResultList")
    @WebResult(name = "RetrieveResultListResult", partName = "RetrieveResultListResult")
    public String retrieveResultList(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveStatistics", action = "http://wsdl.echelon.com/Panoramix/RetrieveStatistics")
    @WebResult(name = "RetrieveStatisticsResult", partName = "RetrieveStatisticsResult")
    public String retrieveStatistics(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey);

    /**
     * 
     * @param sDeviceID
     * @param sKey
     * @param sAttributeID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UnassignAttribute", action = "http://wsdl.echelon.com/Panoramix/UnassignAttribute")
    @WebResult(name = "UnassignAttributeResult", partName = "UnassignAttributeResult")
    public String unassignAttribute(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sAttributeID", partName = "sAttributeID")
        String sAttributeID);

    /**
     * 
     * @param sDeviceID
     * @param sKey
     * @param sHierarchyLevelMemberID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UnassignHierarchy", action = "http://wsdl.echelon.com/Panoramix/UnassignHierarchy")
    @WebResult(name = "UnassignHierarchyResult", partName = "UnassignHierarchyResult")
    public String unassignHierarchy(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sHierarchyLevelMemberID", partName = "sHierarchyLevelMemberID")
        String sHierarchyLevelMemberID);

    /**
     * 
     * @param sDeviceID
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Update", action = "http://wsdl.echelon.com/Panoramix/Update")
    @WebResult(name = "UpdateResult", partName = "UpdateResult")
    public String update(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sDeviceID", partName = "sDeviceID")
        String sDeviceID,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateCommand", action = "http://wsdl.echelon.com/Panoramix/UpdateCommand")
    @WebResult(name = "UpdateCommandResult", partName = "UpdateCommandResult")
    public String updateCommand(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

    /**
     * 
     * @param sKey
     * @param sXmlParameters
     * @param sResultID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateResult", action = "http://wsdl.echelon.com/Panoramix/UpdateResult")
    @WebResult(name = "UpdateResultResult", partName = "UpdateResultResult")
    public String updateResult(
        @WebParam(name = "sKey", partName = "sKey")
        String sKey,
        @WebParam(name = "sResultID", partName = "sResultID")
        String sResultID,
        @WebParam(name = "sXmlParameters", partName = "sXmlParameters")
        String sXmlParameters);

}
