package com.echelon.wsdl.panoramix;

import javax.inject.Inject;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */

@WebServiceClient(name = "DeviceManager", targetNamespace = "http://wsdl.echelon.com/Panoramix/")
public class DeviceManager extends Service
{
    @Inject
    public DeviceManager(WSDLConfig config) {
        super(config.getWsdlDeviceManager(), config.getDeviceManagerQname());
    }

    /**
     *
     * @return
     *     returns DeviceManagerSoap
     */
    @WebEndpoint(name = "DeviceManagerSoap")
    public DeviceManagerSoap getDeviceManagerSoap() {
        return super.getPort(new QName("http://wsdl.echelon.com/Panoramix/", "DeviceManagerSoap"), DeviceManagerSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceManagerSoap
     */
    @WebEndpoint(name = "DeviceManagerSoap")
    public DeviceManagerSoap getDeviceManagerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsdl.echelon.com/Panoramix/", "DeviceManagerSoap"), DeviceManagerSoap.class, features);
    }

}
