SELECT *
FROM
  PEC_METER_READING_PHOTO,
  PEC_METER_READING,
  PEC_METER_REGISTER,
  PEC_METER
WHERE
  (PEC_METER_READING_PHOTO.PHOTO_EXPORTED = 'N' OR PEC_METER_READING_PHOTO.PHOTO_EXPORTED IS NULL) AND
  PEC_METER_READING.METER_READING_ID = PEC_METER_READING_PHOTO.METER_READING_ID AND
  PEC_METER_READING.METER_REGISTER_ID = PEC_METER_REGISTER.REGISTER_ID AND
  PEC_METER_REGISTER.METER_ID = PEC_METER.METER_ID;