select *
from
  ice_meter,ICE_METERCONSDISTR left join ICE_PROPERTY p1 on ICE_METERCONSDISTR.ICE_PROPERTY_ID = p1.ICE_PROPERTY_ID,
  ICE_METERCONSDISTRLINE left join ICE_PROPERTY p2 on ICE_METERCONSDISTRLINE.ICE_DISTRIBUTIONPROPERTY_ID = p2.ICE_PROPERTY_ID
  left join ICE_METER_REGISTER on ICE_METERCONSDISTRLINE.ICE_METER_REGISTER_ID = ICE_METER_REGISTER.ICE_METER_REGISTER_ID
where
  ICE_METERCONSDISTR.ICE_METERCONSDISTR_ID = ICE_METERCONSDISTRLINE.ICE_METERCONSDISTR_ID and
  ICE_METERCONSDISTRLINE.ice_meter_id = ice_meter.ICE_METER_ID
order by ICE_METERCONSDISTR.ICE_METERCONSDISTR_ID,ICE_METERCONSDISTR.SEQNO,ICE_METERCONSDISTRLINE.SEQNO