select *
from ICE_APPROVEDMETERREADINGS_V
         left join ICE_PROPERTY on ICE_APPROVEDMETERREADINGS_V.ICE_PROPERTY_ID = ICE_PROPERTY.ICE_PROPERTY_ID
         left join ICE_METERREADINGLIST on ICE_APPROVEDMETERREADINGS_V.ICE_METERREADINGLIST_ID = ICE_METERREADINGLIST.ICE_METERREADINGLIST_ID
         left join ICE_METER on ICE_APPROVEDMETERREADINGS_V.ICE_METER_ID = ICE_METER.ICE_METER_ID
         left join ICE_METER_REGISTER on ICE_APPROVEDMETERREADINGS_V.ICE_METER_REGISTER_ID = ICE_METER_REGISTER.ICE_METER_REGISTER_ID
         left join C_UOM on ICE_APPROVEDMETERREADINGS_V.C_UOM_ID = C_UOM.C_UOM_ID
         left join ICE_METERREADINGS on ICE_APPROVEDMETERREADINGS_V.ICE_METERREADINGS_ID = ICE_METERREADINGS.ICE_METERREADINGS_ID
         left join ICE_PRICEVERSIONTIMEOFUSE on ICE_APPROVEDMETERREADINGS_V.M_PRICELIST_VERSION_ID = ICE_PRICEVERSIONTIMEOFUSE.M_PRICELIST_VERSION_ID
         left join ICE_DAYOFWEEK on ICE_PRICEVERSIONTIMEOFUSE.ICE_DAYOFWEEK_ID = ICE_DAYOFWEEK.ICE_DAYOFWEEK_ID
where ICE_METERREADINGLIST.ICE_METERREADINGLISTSTATUS = 'AP'
  and ICE_METERREADINGLIST.ICE_METER_READING_DATE is not null
  and ICE_METERREADINGLIST.ICE_ISPROCESSED = 'N'
order by ICE_METERREADINGLIST.ice_meterreadinglist_id asc