select * from (
select ice_meterReadingdate,ice_meter_reading from ice_meter,ICE_METER_REGISTER,ICE_METERREADINGS
where
  ice_meter.ICE_METER_ID = ICE_METER_REGISTER.ICE_METER_ID and
  ICE_METER_REGISTER.ICE_METER_REGISTER_ID = ICE_METERREADINGS.ICE_METER_REGISTER_ID AND
    ICE_METER.ICE_METER_NUMBER = ? and ICE_METER_REGISTER.ICE_METER_REGISTERID = ? and
    ICE_METERREADINGS.ICE_METERREADINGDATE > ? order by ICE_METERREADINGS.ICE_METERREADINGDATE desc
) where rownum < 2