SELECT *
FROM ICE_METERREADINGLISTITEMS_V,
  ICE_METERREADINGLIST,
  ICE_PROPERTY,
  ICE_METER,
  ICE_METER_REGISTER,
  C_UOM,
  ICE_METERREADINGS
WHERE
  ICE_METERREADINGLISTITEMS_V.ICE_PROPERTY_ID = ICE_PROPERTY.ICE_PROPERTY_ID AND
  ICE_METERREADINGLISTITEMS_V.ICE_METERREADINGLIST_ID = ICE_METERREADINGLIST.ICE_METERREADINGLIST_ID AND
  ICE_METERREADINGLISTITEMS_V.ICE_METER_ID = ICE_METER.ICE_METER_ID AND
  ICE_METERREADINGLISTITEMS_V.ICE_METER_REGISTER_ID = ICE_METER_REGISTER.ICE_METER_REGISTER_ID AND
  ICE_METERREADINGLISTITEMS_V.C_UOM_ID = C_UOM.C_UOM_ID AND
  ICE_METERREADINGLISTITEMS_V.ICE_METERREADINGS_ID = ICE_METERREADINGS.ICE_METERREADINGS_ID AND
  ICE_MeterReadingListStatus = 'AP'