SELECT * from PEC_METER_READING
  left join PEC_METER_REGISTER on PEC_METER_REGISTER.METER_REGISTER_ID = PEC_METER_READING.METER_REGISTER_ID
  left join PEC_METER on PEC_METER.METER_ID = PEC_METER_REGISTER.METER_ID
  left join PEC_UTILITY_METER_READING_LIST on PEC_UTILITY_METER_READING_LIST.UTILITY_METER_READING_LIST_ID = PEC_METER_REGISTER.UTILITY_METER_READING_LIST_ID
where PEC_METER_READING.UTILITY_METER_READING_LIST_ID = ? and (CURRENT_READING > 0 or SMART_READING > 0) order by PEC_METER_READING.REFERENCE_ID asc