update METER_READING_GAP_PROCESSOR
set (METER_SERIAL_N) =
    (select NES_METER.SERIAL_N from NES_METER where NES_METER.METER_ID = METER_READING_GAP_PROCESSOR.METER_ID and METER_READING_GAP_PROCESSOR.METER_TYPE = 'NES')
where
    METER_SERIAL_N is null
  and METER_TYPE = 'NES';

update METER_READING_GAP_PROCESSOR
set (METER_SERIAL_N) =
    (select ELSTER_METER.SERIAL_N from ELSTER_METER where ELSTER_METER.METER_ID = METER_READING_GAP_PROCESSOR.METER_ID and METER_READING_GAP_PROCESSOR.METER_TYPE = 'ELSTER')
where
    METER_SERIAL_N is null
  and METER_TYPE = 'ELSTER';

update METER_READING_GAP_PROCESSOR
set (METER_SERIAL_N) =
    (select GENERIC_METER.METER_SERIAL_N from GENERIC_METER where GENERIC_METER.METER_ID = METER_READING_GAP_PROCESSOR.METER_ID and METER_READING_GAP_PROCESSOR.METER_TYPE = 'GENERIC')
where
    METER_SERIAL_N is null
  and METER_TYPE = 'GENERIC'