left join KAMSTRUP_METER on KAMSTRUP_METER.METER_ID = METER_READING.KAM_METER_ID
       left join ELSTER_METER on ELSTER_METER.METER_ID = METER_READING.ELS_METER_ID
       left join NES_METER on NES_METER.METER_ID = METER_READING.NES_METER_ID
       left join GENERIC_METER on GENERIC_METER.METER_ID = METER_READING.GENERIC_METER_ID