DECLARE ICEOWNER VARCHAR2(40) := '_OWNER_';
        ICEUSER VARCHAR2(40) := '_USERNAME_';
        ICEROLE VARCHAR2(40) := '_ROLE_';
BEGIN
  FOR R IN (SELECT TABLE_NAME FROM USER_TABLES)
  LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE,DELETE,INSERT ON ' ||R.TABLE_NAME||' TO '||ICEROLE;
  END LOOP;
  FOR R IN (SELECT OBJECT_NAME OBJ FROM USER_OBJECTS WHERE OBJECT_TYPE IN ('VIEW','SEQUENCE'))
  LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON '||ICEOWNER||'.'||R.OBJ||' TO '||ICEROLE;
  END LOOP;
  FOR R IN (SELECT OBJECT_NAME OBJ FROM USER_OBJECTS WHERE OBJECT_TYPE IN ('PACKAGE','FUNCTION','PROCEDURE','TYPE'))
  LOOP
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON '||ICEOWNER||'.'||R.OBJ||' TO '||ICEROLE;
  END LOOP;
END;